### ISSUE TITLE
fzf.fish doesn't work immediately after scuba install

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/scuba#2]
#### Describe the bug

Hi @IlanCosman, the bug is as the title says. I also ran into the same problem with `jethrokuan/z`.

#### Steps to reproduce

1. scuba install fzf.fish
2. run `bind`, notice none of the fzf.fish key bindings are in there
3. try to use a key binding, and indeed nothing happens

**Comment by IlanCosman** [comment]
The issue is that these plugins use uninstall.fish. Scuba sources all of the new files, so the bindings get erased. I'll have Scuba ignore uninstall.fish when installing plugins.

**Comment by PatrickF1** [comment]
Ahhhh my bad! I'll go fix that for fzf.fish. As for z, that's weird Jethro implemented it that way because in the z readme, it doesn't even mention OMF, only fisher.

**Comment by IlanCosman** [comment]
uninstall.fish is a facet of both OMF and Fisher. Ironically Jorge introduced it in both places.

**Comment by jorgebucaran** [comment]
Haha guilty as charged. 🙇
