### ISSUE TITLE
scuba vs fisher

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/scuba#3]
Hi @IlanCosman, thanks so much for making this plugin manager! The code and docs look very clean!

As a current fisher user myself, I'm curious why I should switch.
1. What are the pros and cons of both?
2. How come you chose to implement scuba using a bunch of universal environment variables? It seems to me like it would cause shell startup to be slower but I'm not sure. It also makes it hard to "save" scuba state, e.g. into dotfiles.
3. Do you know if plugins that are currently designed for OMF or fisher are compatible with scuba?

Thanks!

**Comment by IlanCosman** [comment]
Yes, the docs need a bunch of work 😄 I think you may have mistyped. What do you mean by "implement z"?

**Comment by PatrickF1** [comment]
Ah my bad, fixed the typo haha

**Comment by IlanCosman** [comment]
The first and third questions are very useful, and I'll add the answers to the Readme 😄. The second question I can answer right now though, and I don't think it warrants being in the readme.

Universal variables are the default way of doing it. Files are what's strange here. Every time I want to access the list of plugins, I would have to parse the file into... variables. Just local ones.

For shell startup, that's a reasonable concern, but ends up being entirely a non-issue.

With a clean shell, try the following.

```fish
time fish -i -c 'exit'
```

I get a little under 5ms.

Now set _1000_ universal variables.

```fish
for i in (seq 1000)
    set -U foo_"$i" hello_"$i"
end
```

You can verify the number with `set | count`.

Then, poll the startup time again using the method above. I get a around 5.8ms. Thus, universal variables are not an issue for shell startup 😄

As for dotfiles, that's not a bad point, but

`fishfile`:
```console
foo/bar
bar/baz
qux/quz
```

can be easily translated into

```console
scuba install \
foo/bar \
bar/baz \
qux/quz
```

And then simply source the file on install. Granted this is a little more annoying, but saves Scuba the massive hassle of dealing with files.

**Comment by PatrickF1** [comment]
> Every time I want to access the list of plugins, I would have to parse the file into... variables. Just local ones.

I'm sorry I don't quite understand what's so hard about that. Could you explain it a bit more? maybe with a code example from fisher or something else?

> I get a around 5.8ms.

Good testing! Agreed that ~0.8 ms is not a big issue.

> And then simply source the file on install

I agree it's not hard to do it with an install script but the advantage of fisher is that it maintains the file for you. I may often forget to update the install script when I add or remove plugins.

**Comment by IlanCosman** [comment]
re: files vs variables

I could do it. It's not really hard at all technically. 

```fish
set blah (cat $file)
```

It's more that the whole process of reading and then writing to the file is a tacked on step that doesn't need to be there, and is less elegant and less well supported than just using universal variables. I suppose I'm willing to do it if people are clamoring for it, but I wouldn't be pleased. It's not the natural way of doing it.

**Comment by PatrickF1** [comment]
Ah I see. Yeah writing it back is pretty annoying.
I still think the point of good tools is to make the user's life easier and hide away all the complexity, meaning sometimes these sacrifices have to be made. But, I may the one of the few people who don't like this. Thanks for explaining.
