### ISSUE TITLE
scuba remove does not expand relative paths to absolute path

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/scuba#4]
#### Describe the bug

When trying to remove a plugin that was installed via path locally, scuba does not expand relative paths to the absolute path. This does not mirror scuba install's behavior, which does expand relative paths.

#### Steps to reproduce

1. Navigate to a local plugin
2. scuba install .
3. scuba remove .
4. » error: . not found

**Comment by IlanCosman** [comment]
Great point! I'll fix that 😄
